apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: web-server
  name: web-server
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 80
  selector:
    io.kompose.service: web-server
status:
  loadBalancer: {}
